Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -44,7 +44,10 @@ steps:
           echo "File found. Displaying contents:"
           cat hello-python-app/k8s/deployment.yaml
           echo "Updating image..."
-          sed -i "s|image:.*|image: gcr.io/elite-flow-446700-k5/python-app:$SHORT_SHA|g" hello-python-app/k8s/deployment.yaml
+          sed -i "s|image:.*|image: gcr.io/elite-flow-446700-k5/python-app:${SHORT_SHA}|g" hello-python-app/k8s/deployment.yaml || {
+            echo "Error: Failed to update image in deployment.yaml"
+            exit 1
+          }
           echo "Updated file contents:"
           cat hello-python-app/k8s/deployment.yaml
         else
