Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -40,18 +40,18 @@ steps:
       - '-c'
       - |
         echo "Checking for deployment.yaml..."
-        if [ -f hello-python-app/k8s/deployment.yaml ]; then
+        if [ -f hello-python-app/deployment.yaml ]; then
           echo "File found. Displaying contents:"
-          cat hello-python-app/k8s/deployment.yaml
+          cat hello-python-app/deployment.yaml
           echo "Updating image..."
-          sed -i "s|image:.*|image: gcr.io/elite-flow-446700-k5/python-app:${SHORT_SHA}|g" hello-python-app/k8s/deployment.yaml || {
+          sed -i "s|image:.*|image: gcr.io/elite-flow-446700-k5/python-app:${SHORT_SHA}|g" hello-python-app/deployment.yaml || {
             echo "Error: Failed to update image in deployment.yaml"
             exit 1
           }
           echo "Updated file contents:"
-          cat hello-python-app/k8s/deployment.yaml
+          cat hello-python-app/deployment.yaml
         else
-          echo "Error: File hello-python-app/k8s/deployment.yaml not found"
+          echo "Error: File hello-python-app/deployment.yaml not found"
           exit 1
         fi
 
@@ -60,9 +60,9 @@ steps:
     args:
       - 'apply'
       - '-f'
-      - 'hello-python-app/k8s/deployment.yaml'
+      - 'hello-python-app/deployment.yaml'
       - '-f'
-      - 'hello-python-app/k8s/service.yaml'
+      - 'hello-python-app/service.yaml'
 
   # Step 7: Check rollout status to ensure the deployment is successful
   - name: 'gcr.io/cloud-builders/kubectl'
